import { ComponentConfig } from "../../types";

export const buttonConfig: ComponentConfig = {
  name: "button",
  filepath: "./index.tsx",
  hipDependencies: [
    "../theme/color.stylex.tsx",
    "../theme/spacing.stylex.tsx",
    "../theme/radius.stylex.tsx",
    "../theme/semantic-color.stylex.tsx",
    "../theme/typography.stylex.tsx",
    "../theme/shadow.stylex.tsx",
    "../theme/useButtonStyles.ts",
    "./context.ts",
    "../theme/types.ts",
    "../theme/colors/amber.stylex.tsx",
    "../theme/colors/blue.stylex.tsx",
    "../theme/colors/bronze.stylex.tsx",
    "../theme/colors/brown.stylex.tsx",
    "../theme/colors/crimson.stylex.tsx",
    "../theme/colors/cyan.stylex.tsx",
    "../theme/colors/gold.stylex.tsx",
    "../theme/colors/grass.stylex.tsx",
    "../theme/colors/gray.stylex.tsx",
    "../theme/colors/green.stylex.tsx",
    "../theme/colors/indigo.stylex.tsx",
    "../theme/colors/iris.stylex.tsx",
    "../theme/colors/jade.stylex.tsx",
    "../theme/colors/lime.stylex.tsx",
    "../theme/colors/mauve.stylex.tsx",
    "../theme/colors/mint.stylex.tsx",
    "../theme/colors/olive.stylex.tsx",
    "../theme/colors/orange.stylex.tsx",
    "../theme/colors/pink.stylex.tsx",
    "../theme/colors/plum.stylex.tsx",
    "../theme/colors/purple.stylex.tsx",
    "../theme/colors/red.stylex.tsx",
    "../theme/colors/ruby.stylex.tsx",
    "../theme/colors/sage.stylex.tsx",
    "../theme/colors/sand.stylex.tsx",
    "../theme/colors/sky.stylex.tsx",
    "../theme/colors/slate.stylex.tsx",
    "../theme/colors/teal.stylex.tsx",
    "../theme/colors/tomato.stylex.tsx",
    "../theme/colors/violet.stylex.tsx",
    "../theme/colors/yellow.stylex.tsx",
  ],
  dependencies: {
    "react-aria-components": "^1.13.0",
  },
};
