packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.1"
  "react": "19.2.0"
  "react-dom": "19.2.0"
  "typescript": "5.9.3"
  "@react-stately/utils": "3.10.8"
  "@react-types/overlays": "3.9.2"
  "@stylexjs/stylex": "0.16.2"
  "lucide-react": "0.545.0"
  "react-aria": "3.44.0"
  "react-aria-components": "1.13.0"
  "react-stately": "3.42.0"
  "change-case": "5.4.4"
  "dedent": "1.7.0"
  "eslint": "9.37.0"
  "@types/node": "22.15.3"
