/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DocsInvoiceAppRouteImport } from './routes/_docs.invoice-app'
import { Route as DocsEcommerceAppRouteImport } from './routes/_docs.ecommerce-app'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInvoiceAppRoute = DocsInvoiceAppRouteImport.update({
  id: '/_docs/invoice-app',
  path: '/invoice-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsEcommerceAppRoute = DocsEcommerceAppRouteImport.update({
  id: '/_docs/ecommerce-app',
  path: '/ecommerce-app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/ecommerce-app': typeof DocsEcommerceAppRoute
  '/invoice-app': typeof DocsInvoiceAppRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/ecommerce-app': typeof DocsEcommerceAppRoute
  '/invoice-app': typeof DocsInvoiceAppRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/_docs/ecommerce-app': typeof DocsEcommerceAppRoute
  '/_docs/invoice-app': typeof DocsInvoiceAppRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/ecommerce-app' | '/invoice-app' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/ecommerce-app' | '/invoice-app' | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/_docs/ecommerce-app'
    | '/_docs/invoice-app'
    | '/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  DocsEcommerceAppRoute: typeof DocsEcommerceAppRoute
  DocsInvoiceAppRoute: typeof DocsInvoiceAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/invoice-app': {
      id: '/_docs/invoice-app'
      path: '/invoice-app'
      fullPath: '/invoice-app'
      preLoaderRoute: typeof DocsInvoiceAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/ecommerce-app': {
      id: '/_docs/ecommerce-app'
      path: '/ecommerce-app'
      fullPath: '/ecommerce-app'
      preLoaderRoute: typeof DocsEcommerceAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  DocsEcommerceAppRoute: DocsEcommerceAppRoute,
  DocsInvoiceAppRoute: DocsInvoiceAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
