/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsInvoiceAppRouteImport } from './routes/_docs.invoice-app'
import { Route as DocsEcommerceAppRouteImport } from './routes/_docs.ecommerce-app'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInvoiceAppRoute = DocsInvoiceAppRouteImport.update({
  id: '/invoice-app',
  path: '/invoice-app',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEcommerceAppRoute = DocsEcommerceAppRouteImport.update({
  id: '/ecommerce-app',
  path: '/ecommerce-app',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecommerce-app': typeof DocsEcommerceAppRoute
  '/invoice-app': typeof DocsInvoiceAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecommerce-app': typeof DocsEcommerceAppRoute
  '/invoice-app': typeof DocsInvoiceAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/ecommerce-app': typeof DocsEcommerceAppRoute
  '/_docs/invoice-app': typeof DocsInvoiceAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ecommerce-app' | '/invoice-app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ecommerce-app' | '/invoice-app'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/_docs/ecommerce-app'
    | '/_docs/invoice-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/invoice-app': {
      id: '/_docs/invoice-app'
      path: '/invoice-app'
      fullPath: '/invoice-app'
      preLoaderRoute: typeof DocsInvoiceAppRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/ecommerce-app': {
      id: '/_docs/ecommerce-app'
      path: '/ecommerce-app'
      fullPath: '/ecommerce-app'
      preLoaderRoute: typeof DocsEcommerceAppRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsEcommerceAppRoute: typeof DocsEcommerceAppRoute
  DocsInvoiceAppRoute: typeof DocsInvoiceAppRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsEcommerceAppRoute: DocsEcommerceAppRoute,
  DocsInvoiceAppRoute: DocsInvoiceAppRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
